### ISSUE TITLE
Flag Emoji

### ISSUE THREAD

**Issue by pento** [pento/x1f4a9#5]
Flag emoji are made of two different characters from the [Regional Indicator Symbol range](https://en.wikipedia.org/wiki/Regional_Indicator_Symbol).

Twemoji handles this fine, but we'll need to add some extra logic to `wp_encode_emoji()`, when we embed static images.

**Comment by shield-9** [comment]
At this time, 219 flags are is available in Unicode.(http://blog.emojipedia.org/209-new-emoji-flags-available-today)

I think it is one of solutions to match them by `preg_match_all('/(\xF0\x9F\x87[\xA6-\xBF]){2}/', $content, $matches )` before existing `preg_match_all()`.

The problem is Twemoji is supporting only 10 flags...(Reported: [twitter/twemoji #44](https://github.com/twitter/twemoji/issues/44))

**Comment by pento** [comment]
Yeah, I think we can naively assume any combination of those characters is meant to indicate a flag.

Also worth noting that Firefox OSX doesn't translate these characters into flags - we should fall back to Twemoji when they're not displayed correctly.

**Comment by pento** [comment]
Oops, forgot to mention this ticket in 3c98087343b1b6f9148765840e66c8463f6fe87b.
